name: Sync multiple branches
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Merge main -> brainpy-2.2.x
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: brainpy-2.2.x
          github_token: ${{ github.token }}